name: LinuxDev

on:
  push:
    branches: [ linux ]
  pull_request:
    branches: [ linux ]
    
jobs:

  build-MacOS:
    
    runs-on: ubuntu-20.04

    steps:

    - uses: actions/checkout@v2

    - name: Retrieve submodules
      run: git submodule update --init --recursive
    
    - name: Build Python
      run: |
        sudo apt-get install xorg-dev
        cd Dependencies/cpython
        mkdir debug
        cd debug
        ../configure --enable-shared --prefix==$PWD
        sudo make && sudo make install
        cp pyconfig.h Include/pyconfig.h
        cd ..
        cd ..
        cd ..
        pip3 install wheel
        pip3 install twine
        mkdir cmake-build-release
        cd cmake-build-release
        cmake ..
