name: LinuxDev

on:
  push:
    branches: [ development ]
  pull_request:
    branches: [ development ]
    
jobs:

  build-Ubuntu:
    
    runs-on: ubuntu-20.04

    steps:

    - uses: actions/checkout@v2

    - name: Retrieve submodules
      run: git submodule update --init --recursive
    
    - name: Build Python
      run: |
        sudo apt-get install xorg-dev
        cd Dependencies/cpython
        mkdir debug
        cd debug
        ../configure --enable-shared --prefix $PWD
        sudo make && sudo make install
        cd ..
        cd ..
        cd ..
        pip3 install wheel
        pip3 install twine
        mkdir cmake-build-release
        cd cmake-build-release
        cmake ..

    - name: Build DearPyGui
      run: |
        cmake --build cmake-build-release --config Release

    - name: Distrubute Test DearPyGui
      run: |
        cd /home/runner/work/DearPyGui/DearPyGui/Distribution/Linux
        python3 BuildPythonWheel.py
        python3 -m setup bdist_wheel --plat-name manylinux1_x86_64 --dist-dir ../../dist
        python3 -m twine upload --repository testpypi ../../dist/* -u __token__ -p ${{ secrets.test_pypi_password }}