name: MacOs

on:
  push:
    branches: [ macos ]
  pull_request:
    branches: [ macos ]
    
jobs:

  build-macOS:
    
    runs-on: MacOS-latest

    steps:

    - uses: actions/checkout@v2

    - name: Retrieve submodules
      run: git submodule update --init --recursive
    
    - name: configure
      run: |
        cd Dependencies/cpython
        ./configure --enable-framework
        sudo make && sudo make install
        cp pyconfig.h Include/pyconfig.h
        cd ..
        cd ..
        mkdir cmake-build-release
        cd cmake-build-release
        cmake ..

    - name: build
      run: |
        cmake --build cmake-build-release --config Release

    - uses: actions/upload-artifact@v2
      with:
        name: dearpygui
        path: ./DearPyGui/dearpygui.so