name: MacOSDev

on:
  push:
    branches: [ development ]
  pull_request:
    branches: [ development ]
    
jobs:

  build-MacOS:
    
    runs-on: MacOS-latest

    steps:

    - uses: actions/checkout@v2

    - name: Retrieve submodules
      run: git submodule update --init --recursive
    
    - name: Build Python
      run: |
        brew install openssl
        cd Dependencies/cpython
        ./configure --enable-framework --with-openssl=$(brew --prefix openssl)
        sudo make && sudo make install
        cp pyconfig.h Include/pyconfig.h
        cd ..
        cd ..
        pip3 install wheel
        pip3 install twine
        mkdir cmake-build-release
        cd cmake-build-release
        cmake ..

    - name: Build DearPyGui
      run: |
        cmake --build cmake-build-release --config Release

    - name: Build Test DearPyGui Wheel
      run: |
        cd /Users/runner/work/DearPyGui/DearPyGui/Distribution
        python3 BuildPythonWheel.py /../cmake-build-release/DearPyGui/dearpygui.so dearpygui.so
        python3 -m setup bdist_wheel --plat-name macosx-10.6-x86_64 --dist-dir ../dist

    - name: Upload Test DearPyGui Wheel
      if: "!contains(github.event.head_commit.message, 'upload skip')"
      run: |
        python3 -m twine upload --repository testpypi ../dist/* -u __token__ -p ${{ secrets.test_pypi_password }} --skip-existing
