name: MacOs

on:
  push:
    branches: [ macos ]
  pull_request:
    branches: [ macos ]
    
jobs:

  build-MacOS:
    
    runs-on: MacOS-latest

    steps:

    - uses: actions/checkout@v2

    - name: Retrieve submodules
      run: git submodule update --init --recursive
    
    - name: configure
      run: |
        brew install openssl
        cd Dependencies/cpython
        ./configure --enable-framework --with-openssl=$(brew --prefix openssl)
        sudo make && sudo make install
        cp pyconfig.h Include/pyconfig.h
        cd ..
        cd ..
        pip3 install wheel
        pip3 install twine
        mkdir cmake-build-release
        cd cmake-build-release
        cmake ..

    - name: build
      run: |
        cmake --build cmake-build-release --config Release

    - name: distrubute
      run: |
        cd ..
        cd /Users/runner/work/DearPyGui/DearPyGui/Distribution/Apple
        chmod +x ./DistributeTestWheel.sh
        ./DistributeTestWheel.sh

    - name: Publish package to TestPyPI
      uses: pypa/gh-action-pypi-publish@master
      with:
        user: RaylockLLC
        password: ${{ secrets.test_pypi_password }}
        repository_url: https://test.pypi.org/simple/ dearpygui