name: Master Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:

  build-windows:
    
    runs-on: windows-2019

    steps:

    - uses: actions/checkout@v2

    - name: Retrieve submodules
      shell: cmd
      run: git submodule update --init --recursive
      
    - name: Build Python
      shell: cmd
      run: |
        cd Scripts
        call BuildPythonForWindows.bat --ci
        cd ..
        mkdir cmake-build-release
        mkdir cmake-build-release32
        cd cmake-build-release
        cmake ..
        cd ..
        cd cmake-build-release32
        cmake .. -G "Visual Studio 16 2019" -A Win32 -DCONFIG_32BIT=True
        
    - name: Build DearPyGui
      shell: cmd
      run: |
        cmake --build cmake-build-release --config Release
        cmake --build cmake-build-release32 --config Release 

  build-MacOS:
    
    runs-on: MacOS-latest

    steps:

    - uses: actions/checkout@v2

    - name: Retrieve submodules
      run: git submodule update --init --recursive
    
    - name: Build Python
      run: |
        brew install openssl
        cd Dependencies/cpython
        ./configure --enable-framework --with-openssl=$(brew --prefix openssl)
        sudo make && sudo make install
        cp pyconfig.h Include/pyconfig.h
        cd ..
        cd ..
        mkdir cmake-build-release
        cd cmake-build-release
        cmake ..

    - name: Build DearPyGui
      run: |
        cmake --build cmake-build-release --config Release
