name: Windows

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:

  build-windows:
    
    runs-on: windows-2019

    steps:

    - uses: actions/checkout@v2
      
    - name: configure
      shell: cmd
      run: |
        cd Scripts
        start BuildPythonForWindows.bat
        cd ..
        mkdir cmake-build-release
        cd cmake-build-release
        cmake ..
        
    - name: build
      run: |
        cmake --build cmake-build-release
