name: Windows

on:
  push:
    branches: [ macos ]
  pull_request:
    branches: [ macos ]
    
jobs:

  build-windows:
    
    runs-on: windows-2019

    steps:

    - uses: actions/checkout@v2

    - name: Retrieve submodules
      shell: cmd
      run: git submodule update --init --recursive
      
    - name: configure
      shell: cmd
      run: |
        cd Scripts
        call BuildPythonForWindows.bat --ci
        cd ..
        mkdir cmake-build-release
        cd cmake-build-release
        cmake ..
        
    - name: build
      shell: cmd
      run: |
        cmake --build cmake-build-release --config Release
        dir
        cd Distribution
        cd Win64
        dir
        call DistributeTestWheel.bat
        python -m twine upload --repository testpypi ../../dist/* -u __token__ -p ${{ secrets.test_pypi_password }}
