name: Windows

on:
  push:
    branches: [ macos ]
  pull_request:
    branches: [ macos ]
    
jobs:

  build-windows:
    
    runs-on: windows-2019

    steps:

    - uses: actions/checkout@v2

    - name: Retrieve submodules
      shell: cmd
      run: git submodule update --init --recursive
      
    - name: configure
      shell: cmd
      run: |
        cd Scripts
        call BuildPythonForWindows.bat --ci
        cd ..
        mkdir cmake-build-release
        cd cmake-build-release
        cmake ..
        
    - name: build
      shell: cmd
      run: |
        cmake --build cmake-build-release --config Release
        dir
        cd Distribution
        cd Win64
        dir
        call DistributeTestWheel.bat

    - name: Publish package to TestPyPI
      uses: pypa/gh-action-pypi-publish@master
      with:
        user: RaylockLLC
        password: ${{ secrets.test_pypi_password }}
        repository_url: https://test.pypi.org/simple/ dearpygui
